<%@ page import="java.util.Locale" %>
<%@ page import="java.util.ResourceBundle" %>

<portlet:defineObjects />
<%
	Locale locale = renderRequest.getLocale();
	ResourceBundle resource = portletConfig.getResourceBundle(locale);
%>

<c:set var="selectfaculty" value='<%= resource.getString("select-faculty") %>'/>
<c:set var="selectproducer" value='<%= resource.getString("select-producer") %>'/>
<c:set var="selectsemester" value='<%= resource.getString("select-semester") %>'/>
<c:set var="selectstatus" value='<%= resource.getString("select-status") %>'/>
<c:set var="approved" value='<%= resource.getString("approved") %>'/>
<c:set var="pending" value='<%= resource.getString("pending") %>'/>
<c:set var="addnewlectureserie" value='<%= resource.getString("add-new-lecture-serie") %>'/>
<c:set var="yourareabouttodeletealllectureseriedata" value='<%= resource.getString("your-are-about-to-delete-all-lecture-serie-data") %>'/>
<c:set var="deletelectureserie" value='<%= resource.getString("delete-lecture-serie") %>'/>
<c:set var="donotallowlectureserie" value='<%= resource.getString("do-not-allow-lecture-serie") %>'/>
<c:set var="allowlectureserie" value='<%= resource.getString("allow-lecture-serie") %>'/>
<c:set var="nolecturefound" value='<%= resource.getString("no-lecture-found") %>'/>
<c:set var="gotofirstpage" value='<%= resource.getString("go-to-first-page") %>'/>
<c:set var="gotopage" value='<%= resource.getString("go-to-page") %>'/>
<c:set var="gotolastpage" value='<%= resource.getString("go-to-last-page") %>'/>
<c:set var="from" value='<%= resource.getString("from") %>'/>
<c:set var="page" value='<%= resource.getString("page") %>'/>
<c:set var="filter" value='<%= resource.getString("filter") %>'/>
<c:set var="resultspersite" value='<%= resource.getString("results-per-site") %>'/>
<c:set var="pleasecorrectinput" value='<%= resource.getString("please-correct-input") %>'/>
<c:set var="lectureid" value='<%= resource.getString("lecture-id") %>'/>
<c:set var="enterlectureid" value='<%= resource.getString("enter-lecture-id") %>'/>
<c:set var="lecturename" value='<%= resource.getString("lecture-name") %>'/>
<c:set var="enterlecturename" value='<%= resource.getString("enter-lecture-name") %>'/>
<c:set var="selectlecturetype" value='<%= resource.getString("select-lecture-type") %>'/>
<c:set var="facilities" value='<%= resource.getString("facilities") %>'/>
<c:set var="add" value='<%= resource.getString("add") %>'/>
<c:set var="pleaceaddfacility" value='<%= resource.getString("pleace-add-facility") %>'/>
<c:set var="producer" value='<%= resource.getString("producer") %>'/>
<c:set var="addoneproducer" value='<%= resource.getString("add-one-producer") %>'/>
<c:set var="shortdescription" value='<%= resource.getString("short-description") %>'/>
<c:set var="semester" value='<%= resource.getString("semester") %>'/>
<c:set var="addnewsemester" value='<%= resource.getString("add-new-semester") %>'/>
<c:set var="languages" value='<%= resource.getString("languages") %>'/>
<c:set var="addonelanguage" value='<%= resource.getString("add-one-language") %>'/>
<c:set var="lecturers" value='<%= resource.getString("lecturers") %>'/>
<c:set var="exampleprofname" value='<%= resource.getString("example-prof-name") %>'/>
<c:set var="password" value='<%= resource.getString("password") %>'/>
<c:set var="description" value='<%= resource.getString("description") %>'/>
<c:set var="save" value='<%= resource.getString("save") %>'/>
<c:set var="lecturetype" value='<%= resource.getString("lecture-type") %>'/>
<c:set var="gotooverview" value='<%= resource.getString("go-to-overview") %>'/>
<c:set var="editthisevent" value='<%= resource.getString("edit-this-event") %>'/>
<c:set var="gotooverview" value='<%= resource.getString("go-to-overview") %>'/>
<c:set var="newinstitution" value='<%= resource.getString("new-institution") %>'/>
<c:set var="newinstitution" value='<%= resource.getString("new-institution") %>'/>
<c:set var="choosestreamer" value='<%= resource.getString("choose-streamer") %>'/>
<c:set var="rootdirectory" value='<%= resource.getString("root-directory") %>'/>
<c:set var="order" value='<%= resource.getString("order") %>'/>
<c:set var="up" value='<%= resource.getString("up") %>'/>
<c:set var="down" value='<%= resource.getString("down") %>'/>
<c:set var="reallydeleteinstitution" value='<%= resource.getString("really-delete-institution") %>'/>
<c:set var="deleteinstitution" value='<%= resource.getString("delete-institution") %>'/>
<c:set var="httpstreamer" value='<%= resource.getString("http-streamer") %>'/>
<c:set var="edit" value='<%= resource.getString("edit") %>'/>
<c:set var="zb" value='<%= resource.getString("zb") %>'/>
<c:set var="orip" value='<%= resource.getString("or-ip") %>'/>
<c:set var="httpstreamerlist" value='<%= resource.getString("http-streamer-list") %>'/>
<c:set var="reallydeletestreamer" value='<%= resource.getString("really-delete-streamer") %>'/>
<c:set var="deletestreamer" value='<%= resource.getString("delete-streamer") %>'/>
<c:set var="addnewhttpstreamer" value='<%= resource.getString("add-new-http-streamer") %>'/>
<c:set var="zb" value='<%= resource.getString("zb") %>'/>
<c:set var="resultspersite" value='<%= resource.getString("results-per-site") %>'/>
<c:set var="chooserole" value='<%= resource.getString("choose-role") %>'/>
<c:set var="username" value='<%= resource.getString("user-name") %>'/>
<c:set var="student" value='<%= resource.getString("student") %>'/>
<c:set var="coordinator" value='<%= resource.getString("coordinator") %>'/>
<c:set var="l2gadmin" value='<%= resource.getString("l2gadmin") %>'/>
<c:set var="producer" value='<%= resource.getString("producer") %>'/>
<c:set var="state" value='<%= resource.getString("state") %>'/>
<c:set var="stopped" value='<%= resource.getString("stopped") %>'/>
<c:set var="started" value='<%= resource.getString("started") %>'/>
<c:set var="threadisupdatedevery" value='<%= resource.getString("thread-is-updated-every") %>'/>
<c:set var="start" value='<%= resource.getString("start") %>'/>
<c:set var="stop" value='<%= resource.getString("stop") %>'/>
<c:set var="milliseconds" value='<%= resource.getString("milliseconds") %>'/>

<c:set var="chooseproducer" value='<%= resource.getString("choose-producer") %>'/>
<c:set var="selectlectureseries" value='<%= resource.getString("select-lecture-series") %>'/>
<c:set var="addnewvideodataset" value='<%= resource.getString("add-new-videodata-set") %>'/>
<c:set var="novideouploaded" value='<%= resource.getString("no-video-uploaded") %>'/>
<c:set var="videomp4" value='<%= resource.getString("video-mp4") %>'/>
<c:set var="audiomp3" value='<%= resource.getString("audio-mp3") %>'/>
<c:set var="audiom4a" value='<%= resource.getString("audio-m4a") %>'/>
<c:set var="iPodm4v" value='<%= resource.getString("iPod-m4v") %>'/>
<c:set var="textpdf" value='<%= resource.getString("text-pdf") %>'/>
<c:set var="recordingon" value='<%= resource.getString("recording-on") %>'/>
<c:set var="uploaded-on" value='<%= resource.getString("uploaded-on") %>'/>
<c:set var="uploadandmanagefiles" value='<%= resource.getString("upload-and-manage-files") %>'/>
<c:set var="lockpublicaccess" value='<%= resource.getString("lock-public-access") %>'/>
<c:set var="reallypickupopenaccess" value='<%= resource.getString("really-pick-up-open-access") %>'/>
<c:set var="publicityvisible" value='<%= resource.getString("publicity-visible") %>'/>
<c:set var="reallyavailibletothepublic" value='<%= resource.getString("really-availible-to-the-public") %>'/>
<c:set var="lockdownload" value='<%= resource.getString("lock-download") %>'/>
<c:set var="permitdownload" value='<%= resource.getString("permit-download") %>'/>
<c:set var="addchapterorcomment" value='<%= resource.getString("add-chapter-or-comment") %>'/>
<c:set var="editcommentorchapter" value='<%= resource.getString("edit-comment-or-chapter") %>'/>
<c:set var="editinfo" value='<%= resource.getString("edit-info") %>'/>
<c:set var="reallydeletealldata" value='<%= resource.getString("really-delete-all-data") %>'/>
<c:set var="deletevideo" value='<%= resource.getString("delete-video") %>'/>
<c:set var="language" value='<%= resource.getString("language") %>'/>
<c:set var="videodatasetsaved" value='<%= resource.getString("video-data-set-saved") %>'/>
<c:set var="views" value='<%= resource.getString("views") %>'/>

<c:set var="gotonextpage" value='<%= resource.getString("go-to-next-page") %>'/>


<c:set var="gotooverview" value='<%= resource.getString("go-to-overview") %>'/>
<c:set var="pleasecorrectinput" value='<%= resource.getString("please-correct-input") %>'/>
<c:set var="lectureid" value='<%= resource.getString("lecture-id") %>'/>
<c:set var="enterlectureid" value='<%= resource.getString("enter-lecture-id") %>'/>
<c:set var="lecturename" value='<%= resource.getString("lecture-name") %>'/>
<c:set var="enterlecturename" value='<%= resource.getString("enter-lecture-name") %>'/>
<c:set var="lecturetype" value='<%= resource.getString("lecture-type") %>'/>
<c:set var="selectlecturetype" value='<%= resource.getString("select-lecture-type") %>'/>
<c:set var="facilities" value='<%= resource.getString("facilities") %>'/>
<c:set var="add" value='<%= resource.getString("add") %>'/>
<c:set var="pleaceaddfacility" value='<%= resource.getString("pleace-add-facility") %>'/>
<c:set var="producer" value='<%= resource.getString("producer") %>'/>
<c:set var="addoneproducer" value='<%= resource.getString("add-one-producer") %>'/>
<c:set var="shortdescription" value='<%= resource.getString("short-description") %>'/>
<c:set var="semester" value='<%= resource.getString("semester") %>'/>
<c:set var="addnewsemester" value='<%= resource.getString("add-new-semester") %>'/>
<c:set var="languages" value='<%= resource.getString("languages") %>'/>
<c:set var="addonelanguage" value='<%= resource.getString("add-one-language") %>'/>
<c:set var="lecturers" value='<%= resource.getString("lecturers") %>'/>
<c:set var="exampleprofname" value='<%= resource.getString("example-prof-name") %>'/>
<c:set var="password" value='<%= resource.getString("password") %>'/>
<c:set var="description" value='<%= resource.getString("description") %>'/>
<c:set var="aftersaving" value='<%= resource.getString("after-saving") %>'/>
<c:set var="save" value='<%= resource.getString("save") %>'/>
<c:set var="editthisevent" value='<%= resource.getString("edit-this-event") %>'/>
<c:set var="chapter" value='<%= resource.getString("chapter") %>'/>
<c:set var="comment" value='<%= resource.getString("comment") %>'/>
<c:set var="shorttitle" value='<%= resource.getString("short-title") %>'/>
<c:set var="chapterbeginning" value='<%= resource.getString("chapter-beginning") %>'/>
<c:set var="chapterend" value='<%= resource.getString("chapter-end") %>'/>
<c:set var="text" value='<%= resource.getString("text") %>'/>
<c:set var="delete" value='<%= resource.getString("delete") %>'/>
<c:set var="reallydeletethischapter" value='<%= resource.getString("really-delete-this-chapter") %>'/>
<c:set var="commenton" value='<%= resource.getString("comment-on") %>'/>
<c:set var="commentoff" value='<%= resource.getString("comment-off") %>'/>
<c:set var="playthischapter" value='<%= resource.getString("play-this-chapter") %>'/>
<c:set var="gobacktovideo" value='<%= resource.getString("go-back-to-video") %>'/>
<c:set var="allowsegmentation" value='<%= resource.getString("allow-segmentation") %>'/>

<c:set var="title" value='<%= resource.getString("title") %>'/>
<c:set var="tags" value='<%= resource.getString("tags") %>'/>
<c:set var="author" value='<%= resource.getString("author") %>'/>
<c:set var="videoproducer" value='<%= resource.getString("videoproducer") %>'/>
<c:set var="publisher" value='<%= resource.getString("publisher") %>'/>
<c:set var="description" value='<%= resource.getString("description") %>'/>
<c:set var="l2golicence" value='<%= resource.getString("l2go-licence") %>'/>
<c:set var="byncsa" value='<%= resource.getString("by-nc-sa") %>'/>

<c:set var="selectlectureseries" value='<%= resource.getString("select-lecture-series") %>'/>
<c:set var="addnewvideodataset" value='<%= resource.getString("add-new-videodata-set") %>'/>
<c:set var="novideouploaded" value='<%= resource.getString("no-video-uploaded") %>'/>
<c:set var="videomp4" value='<%= resource.getString("video-mp4") %>'/>
<c:set var="audiomp3" value='<%= resource.getString("audio-mp3") %>'/>
<c:set var="audiom4a" value='<%= resource.getString("audio-m4a") %>'/>
<c:set var="iPodm4v" value='<%= resource.getString("iPod-m4v") %>'/>
<c:set var="textpdf" value='<%= resource.getString("text-pdf") %>'/>
<c:set var="recordingon" value='<%= resource.getString("recording-on") %>'/>
<c:set var="uploaded-on" value='<%= resource.getString("uploaded-on") %>'/>
<c:set var="uploadandmanagefiles" value='<%= resource.getString("upload-and-manage-files") %>'/>
<c:set var="lockpublicaccess" value='<%= resource.getString("lock-public-access") %>'/>
<c:set var="reallypickupopenaccess" value='<%= resource.getString("really-pick-up-open-access") %>'/>
<c:set var="publicityvisible" value='<%= resource.getString("publicity-visible") %>'/>
<c:set var="reallyavailibletothepublic" value='<%= resource.getString("really-availible-to-the-public") %>'/>
<c:set var="lockdownload" value='<%= resource.getString("lock-download") %>'/>
<c:set var="permitdownload" value='<%= resource.getString("permit-download") %>'/>
<c:set var="addchapterorcomment" value='<%= resource.getString("add-chapter-or-comment") %>'/>
<c:set var="editcommentorchapter" value='<%= resource.getString("edit-comment-or-chapter") %>'/>
<c:set var="editinfo" value='<%= resource.getString("edit-info") %>'/>
<c:set var="reallydeletealldata" value='<%= resource.getString("really-delete-all-data") %>'/>
<c:set var="deletevideo" value='<%= resource.getString("delete-video") %>'/>
<c:set var="language" value='<%= resource.getString("language") %>'/>
<c:set var="videodatasetsaved" value='<%= resource.getString("video-data-set-saved") %>'/>
<c:set var="views" value='<%= resource.getString("views") %>'/>

<c:set var="pleasechoosevideofile" value='<%= resource.getString("please-choose-video-file") %>'/>
<c:set var="pleasenotefilesintax" value='<%= resource.getString("please-note-file-sintax") %>'/>
<c:set var="impermissiblefilename" value='<%= resource.getString("impermissible-file-name") %>'/>
<c:set var="upload" value='<%= resource.getString("upload") %>'/>

<c:set var="uploadcantakeawhile" value='<%= resource.getString("upload-can-take-a-while") %>'/>
<c:set var="reallydeletealldata" value='<%= resource.getString("really-delete-all-data") %>'/>
<c:set var="removemp3" value='<%= resource.getString("remove-mp3") %>'/>
<c:set var="removemp4" value='<%= resource.getString("remove-mp4") %>'/>
<c:set var="removeipod" value='<%= resource.getString("remove-ipod") %>'/>
<c:set var="removepdf" value='<%= resource.getString("remove-pdf") %>'/>
<c:set var="embedconditions" value='<%= resource.getString("embed-conditions") %>'/>
<c:set var="urladdress" value='<%= resource.getString("url-address") %>'/>
<c:set var="urladdresstitle" value='<%= resource.getString("url-address-title") %>'/>
<c:set var="embed" value='<%= resource.getString("embed") %>'/>
<c:set var="embedtitle" value='<%= resource.getString("embed-title") %>'/>
<c:set var="embedcommsy" value='<%= resource.getString("embed-commsy") %>'/>
<c:set var="embedcommsytitle" value='<%= resource.getString("embed-commsy-title") %>'/>
<c:set var="removedata" value='<%= resource.getString("remove-data") %>'/>

<c:set var="reallyavailibletothepublick" value='<%= resource.getString("really-availible-to-the-public") %>'/>
<c:set var="reallydeletealldata" value='<%= resource.getString("really-delete-all-data") %>'/>

<c:set var="mp4" value='<%= resource.getString("mp4") %>'/>
<c:set var="duration" value='<%= resource.getString("duration") %>'/>
<c:set var="min" value='<%= resource.getString("min") %>'/>
<c:set var="views" value='<%= resource.getString("views") %>'/>

<c:set var="gotofirstpage" value='<%= resource.getString("go-to-first-page") %>'/>
<c:set var="gotopage" value='<%= resource.getString("go-to-page") %>'/>
<c:set var="page" value='<%= resource.getString("page") %>'/>
<c:set var="gotolastpage" value='<%= resource.getString("go-to-last-page") %>'/>

<c:set var="videodatasetinfo" value='<%= resource.getString("video-data-set-info") %>'/>
<c:set var="reallychangepassword" value='<%= resource.getString("really-change-password") %>'/>
<c:set var="setpassword" value='<%= resource.getString("set-password") %>'/>

<c:set var="youcanapplylectures" value='<%= resource.getString("you-can-apply-lectures") %>'/>
<c:set var="newlectureserierequest" value='<%= resource.getString("new-lecture-serie-request") %>'/>

<c:set var="selectfaculty" value='<%= resource.getString("select-faculty") %>'/>
<c:set var="selectproducer" value='<%= resource.getString("select-producer") %>'/>
<c:set var="selectsemester" value='<%= resource.getString("select-semester") %>'/>
<c:set var="selectstatus" value='<%= resource.getString("select-status") %>'/>
<c:set var="addnewlectureserie" value='<%= resource.getString("add-new-lecture-serie") %>'/>
<c:set var="yourareabouttodeletealllectureseriedata" value='<%= resource.getString("your-are-about-to-delete-all-lecture-serie-data") %>'/>
<c:set var="deletelectureserie" value='<%= resource.getString("delete-lecture-serie") %>'/>
<c:set var="donotallowlectureserie" value='<%= resource.getString("do-not-allow-lecture-serie") %>'/>
<c:set var="allowlectureserie" value='<%= resource.getString("allow-lecture-serie") %>'/>
<c:set var="nolecturefound" value='<%= resource.getString("no-lecture-found") %>'/>
<c:set var="gotofirstpage" value='<%= resource.getString("go-to-first-page") %>'/>
<c:set var="gotopage" value='<%= resource.getString("go-to-page") %>'/>
<c:set var="gotolastpage" value='<%= resource.getString("go-to-last-page") %>'/>
<c:set var="from" value='<%= resource.getString("from") %>'/>
<c:set var="page" value='<%= resource.getString("page") %>'/>
<c:set var="filter" value='<%= resource.getString("filter") %>'/>
<c:set var="resultspersite" value='<%= resource.getString("results-per-site") %>'/>
<c:set var="pleasecorrectinput" value='<%= resource.getString("please-correct-input") %>'/>
<c:set var="lectureid" value='<%= resource.getString("lecture-id") %>'/>
<c:set var="enterlectureid" value='<%= resource.getString("enter-lecture-id") %>'/>
<c:set var="lecturename" value='<%= resource.getString("lecture-name") %>'/>
<c:set var="enterlecturename" value='<%= resource.getString("enter-lecture-name") %>'/>
<c:set var="selectlecturetype" value='<%= resource.getString("select-lecture-type") %>'/>
<c:set var="facilities" value='<%= resource.getString("facilities") %>'/>
<c:set var="add" value='<%= resource.getString("add") %>'/>
<c:set var="pleaceaddfacility" value='<%= resource.getString("pleace-add-facility") %>'/>
<c:set var="producer" value='<%= resource.getString("producer") %>'/>
<c:set var="addoneproducer" value='<%= resource.getString("add-one-producer") %>'/>
<c:set var="shortdescription" value='<%= resource.getString("short-description") %>'/>
<c:set var="semester" value='<%= resource.getString("semester") %>'/>
<c:set var="addnewsemester" value='<%= resource.getString("add-new-semester") %>'/>
<c:set var="languages" value='<%= resource.getString("languages") %>'/>
<c:set var="addonelanguage" value='<%= resource.getString("add-one-language") %>'/>
<c:set var="lecturers" value='<%= resource.getString("lecturers") %>'/>
<c:set var="exampleprofname" value='<%= resource.getString("example-prof-name") %>'/>
<c:set var="password" value='<%= resource.getString("password") %>'/>
<c:set var="description" value='<%= resource.getString("description") %>'/>
<c:set var="save" value='<%= resource.getString("save") %>'/>
<c:set var="lecturetype" value='<%= resource.getString("lecture-type") %>'/>
<c:set var="gotooverview" value='<%= resource.getString("go-to-overview") %>'/>
<c:set var="editthisevent" value='<%= resource.getString("edit-this-event") %>'/>
<c:set var="gotooverview" value='<%= resource.getString("go-to-overview") %>'/>
<c:set var="newinstitution" value='<%= resource.getString("new-institution") %>'/>
<c:set var="newinstitution" value='<%= resource.getString("new-institution") %>'/>
<c:set var="choosestreamer" value='<%= resource.getString("choose-streamer") %>'/>
<c:set var="rootdirectory" value='<%= resource.getString("root-directory") %>'/>
<c:set var="order" value='<%= resource.getString("order") %>'/>
<c:set var="up" value='<%= resource.getString("up") %>'/>
<c:set var="down" value='<%= resource.getString("down") %>'/>
<c:set var="reallydeleteinstitution" value='<%= resource.getString("really-delete-institution") %>'/>
<c:set var="deleteinstitution" value='<%= resource.getString("delete-institution") %>'/>
<c:set var="httpstreamer" value='<%= resource.getString("http-streamer") %>'/>
<c:set var="edit" value='<%= resource.getString("edit") %>'/>
<c:set var="zb" value='<%= resource.getString("zb") %>'/>
<c:set var="orip" value='<%= resource.getString("or-ip") %>'/>
<c:set var="httpstreamerlist" value='<%= resource.getString("http-streamer-list") %>'/>
<c:set var="reallydeletestreamer" value='<%= resource.getString("really-delete-streamer") %>'/>
<c:set var="deletestreamer" value='<%= resource.getString("delete-streamer") %>'/>
<c:set var="addnewhttpstreamer" value='<%= resource.getString("add-new-http-streamer") %>'/>
<c:set var="zb" value='<%= resource.getString("zb") %>'/>
<c:set var="resultspersite" value='<%= resource.getString("results-per-site") %>'/>
<c:set var="chooserole" value='<%= resource.getString("choose-role") %>'/>
<c:set var="username" value='<%= resource.getString("user-name") %>'/>
<c:set var="student" value='<%= resource.getString("student") %>'/>
<c:set var="l2gadmin" value='<%= resource.getString("l2gadmin") %>'/>
<c:set var="producer" value='<%= resource.getString("producer") %>'/>
<c:set var="state" value='<%= resource.getString("state") %>'/>
<c:set var="stopped" value='<%= resource.getString("stopped") %>'/>
<c:set var="started" value='<%= resource.getString("started") %>'/>
<c:set var="threadisupdatedevery" value='<%= resource.getString("thread-is-updated-every") %>'/>
<c:set var="start" value='<%= resource.getString("start") %>'/>
<c:set var="stop" value='<%= resource.getString("stop") %>'/>
<c:set var="milliseconds" value='<%= resource.getString("milliseconds") %>'/>
<c:set var="coordinatorfor" value='<%= resource.getString("coordinator-for") %>'/>
<c:set var="producerfor" value='<%= resource.getString("producer-for") %>'/>
<c:set var="name" value='<%= resource.getString("name") %>'/>
<c:set var="facility" value='<%= resource.getString("facility") %>'/>
<c:set var="citation2go" value='<%= resource.getString("citation2go") %>'/>	
<c:set var="activated" value='<%= resource.getString("activated") %>'/>	
<c:set var="disabled" value='<%= resource.getString("disabled") %>'/>	
<c:set var="languagesforselect" value='<%= resource.getString("languages-for-select") %>'/>
<c:set var="eventtypesforselect" value='<%= resource.getString("event-types-for-select") %>'/>
<c:set var="pleaseselectproducer" value='<%= resource.getString("please-select-producer") %>'/>
<c:set var="novideosforthisproducer" value='<%= resource.getString("no-videos-for-this-producer") %>'/>
<c:set var="pleasechoosefilterunlockedtomanagelectureseries" value='<%= resource.getString("please-choose-filter-unlocked-to-manage-lectureseries") %>'/>
<c:set var="nolectureseriestoapprove" value='<%= resource.getString("no-lectureseries-to-approve") %>'/>
<c:set var="editandapprove" value='<%= resource.getString("edit-and-approve") %>'/>